server {
    listen 80;
    server_name nightfall-interactive.local;
    root /usr/share/nginx/www;
    index index.html;
}

server {
    listen 80;
    server_name forge.nightfall-interactive.local;
    root /usr/share/nginx/forge;
    index index.html;
}

server {
    listen 80;
    server_name mirror-07.nightfall-interactive.local;
    root /usr/share/nginx/mirror;
    index index.html;
}

server {
    listen 80 default_server;
    server_name _;

    location /files/ {
        alias /usr/share/nginx/files/;
	index index.html;
        autoindex off;
    }
}
