server {
    listen 80;
    server_name nightfall-interactive.local;
    location / {
        proxy_pass http://stage1:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name forge.nightfall-interactive.local;
    location / {
        proxy_pass http://stage1:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name mirror-07.nightfall-interactive.local;
    location / {
        proxy_pass http://stage1:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80 default_server;
    server_name _;

    location /files/ {
        proxy_pass http://stage1:80;
        proxy_set_header Host $host;
    }

    location /verify/ {
        proxy_pass http://stage2:5000/verify/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://ctfd:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
